"""Constants partagées NavMAX — ports, timeouts, limites."""

from typing import Final

# Ports standards
PORT_SSH: Final = 22
PORT_SMTP: Final = 25
PORT_HTTP: Final = 80
PORT_HTTPS: Final = 443
PORT_SMB: Final = 445
PORT_LDAP: Final = 389
PORT_LDAPS: Final = 636
PORT_RDP: Final = 3389
PORT_MSSQL: Final = 1433
PORT_MYSQL: Final = 3306
PORT_POSTGRESQL: Final = 5432
PORT_REDIS: Final = 6379
PORT_MONGODB: Final = 27017
PORT_ELASTICSEARCH: Final = 9200
PORT_KAFKA: Final = 9092
PORT_DOCKER_API: Final = 2375
PORT_KUBERNETES_API: Final = 6443
PORT_JENKINS: Final = 8080
PORT_GRAFANA: Final = 3000
PORT_PROMETHEUS: Final = 9090
PORT_MEMCACHED: Final = 11211
PORT_ETCD: Final = 2379
PORT_ZOOKEEPER: Final = 2181
PORT_COUCHDB: Final = 5984

# Timeouts (secondes)
TIMEOUT_CONNECT: Final = 5.0
TIMEOUT_READ: Final = 10.0
TIMEOUT_SCAN: Final = 30.0
TIMEOUT_BRUTEFORCE: Final = 3.0
TIMEOUT_HTTP: Final = 15.0
TIMEOUT_LDAP: Final = 10.0
TIMEOUT_SUBPROCESS: Final = 300

# Limites scanner
SCANNER_MAX_CONCURRENCY: Final = 50
SCANNER_MAX_RETRIES: Final = 3
SCANNER_RETRY_BACKOFF: Final = 1.5
SCANNER_RETRY_BACKOFF_MAX: Final = 30.0

# Limites proxy / intruder
INTRUDER_MAX_PAYLOAD_SIZE: Final = 65_535
INTRUDER_MAX_POSITIONS: Final = 100
PROXY_DEFAULT_PORT: Final = 8080
PROXY_MAX_BODY_SIZE: Final = 10 * 1024 * 1024  # 10 Mo

# AI
AI_MAX_INPUT_LENGTH: Final = 8_000
AI_MAX_PROMPT_LENGTH: Final = 16_000
AI_CIRCUIT_BREAKER_THRESHOLD: Final = 5
AI_CIRCUIT_BREAKER_RESET_S: Final = 60.0

# Auth
JWT_MIN_SECRET_LENGTH: Final = 32
BCRYPT_ROUNDS: Final = 12

# Reporting
CVSS_HIGH_THRESHOLD: Final = 7.0
CVSS_CRITICAL_THRESHOLD: Final = 9.0
